### ISSUE TITLE
There seems to be a serious bug in the file HotpotAdv/consistency.py that leads to incorrect calculation results

### ISSUE THREAD

**Issue by aminvisible** [RuochenZhao/Verify-and-Edit#2]
In **def consistency** (line 55) of HotpotAdv/consistency.py
lines 70, 71, 72:
```
probs = [a[1] for a in answer_prob_lists[final_aggregated_answer]]
best_i = np.argmax(probs)
final_aggregated_rationale = rationales[best_i]
```
This seems to have incorrectly calculated **best_i** and **final_aggregated_rationale**, because of a new list of argmax indices instead of **rationales**.

**Comment by RuochenZhao** [comment]
Hi, sorry! It seems that this problem was fixed later on and I didn't update it. Could you see if the current update solves the problem?

**Comment by aminvisible** [comment]
> Hi, sorry! It seems that this problem was fixed later on and I didn't update it. Could you see if the current update solves the problem?

I think this problem has been fixed now, but are other files up-to-date now?

**Comment by RuochenZhao** [comment]
Yes it was the only issue that wasn't updated. I'll be closing the issue now.
